NRI課題の初回提出です。
shiraosa/sasakiyuya pull request #1
Opened 2020-04-07 06:06 UTC by shiraosa

コードチェッカーは問題なしでした。

2020-04-07 08:03 UTC, fjtawork reviewed
全体的にインデントの見直しをやってみましょう

2020-04-07 08:03 UTC, fjtawork commented on nri-html/index.html
> +     <header>
インデントがズレてるので修正しましょう！
この箇所以外にもいくつかインデントのズレがあるので、全体的に確認してみてください。

インデントは仮にスペースを４つと決めたなら、必ずどのタグのインデントでも４つで統一しましょう。

2020-04-07 09:06 UTC, shiraosa commented
インデントの調整をしました。

2020-04-08 03:43 UTC, piasoratech requested changes
コメントしたので確認をお願いします！
まだタグに対しての理解が浅い気がするので、本や以下のサイトを参考に理解を深めていただきたいです。
https://developer.mozilla.org/ja/docs/Web/HTML/Reference

2020-04-08 03:43 UTC, piasoratech commented on nri-html/index.html
> +    <div class="header-logo-menu">
この`div`はどういった意図で使用しましたか？(指摘ではなく質問です。)

2020-04-08 03:43 UTC, piasoratech commented on nri-html/index.html
> +    </div>
`header`
`main`
`footer`
に属さない要素がないようにしましょう。

2020-04-08 03:43 UTC, piasoratech commented on nri-html/index.html
> +        <div class="title-img-box">
`h`タグを使用されるのであれば`section`タグを使用しましょう。

2020-04-08 03:43 UTC, piasoratech commented on nri-html/index.html
> +            <span>NRIの強み</span>
`span`タグにした意図は何でしょうか？

2020-04-08 03:43 UTC, piasoratech commented on nri-html/index.html
> +        <div class="sub-box">
`h`タグを使用するなら`section`タグを使いましょう

2020-04-08 03:43 UTC, piasoratech commented on nri-html/index.html
> +                </ul>
インデントそろえましょう

2020-04-08 03:57 UTC, shiraosa commented on nri-html/index.html
> +    <div class="header-logo-menu">
`.header-logo-menu * {
    justify-content: space-between;
}*`
を使用しようと考えていました。

2020-04-08 04:23 UTC, shiraosa commented on nri-html/index.html
> +            <span>NRIの強み</span>
h1の上にpがあることに違和感を覚えたことと装飾目的ならspanが適切かなと思いました。

2020-04-09 02:06 UTC, shiraosa commented
HTMLの指摘箇所修正と質問に回答しました。

2020-04-09 02:20 UTC, shiraosa commented
HTMLの修正と質問への回答しました。

2020-04-09 02:21 UTC, shiraosa commented on nri-html/index.html
> +    </div>
修正しました

2020-04-09 02:21 UTC, shiraosa commented on nri-html/index.html
> +        <div class="title-img-box">
セクションタグ使用しました。

2020-04-09 02:23 UTC, shiraosa commented on nri-html/index.html
> +        <div class="sub-box">
sectionタグ使用しました。

2020-04-09 02:23 UTC, shiraosa commented on nri-html/index.html
> +                </ul>
インデント揃えました。

2020-04-09 02:23 UTC, shiraosa commented on nri-html/index.html
> +                </ul>
<b>

2020-04-09 02:24 UTC, shiraosa commented on nri-html/index.html
> +                </ul>
`<b>`

2020-04-09 07:58 UTC, shiraosa commented
セクションとインデントの修正と質問に回答しました。

2020-04-09 08:17 UTC, Yuzunoha commented
LGTMです！！cssに移ってください！！他の講師からhtmlに関する指摘があったら僕のレビューが甘くすみません><

2020-04-13 07:37 UTC, merged