家具屋課題Homeのhtml
shiraosa/sasakiyuya pull request #3
Opened 2020-04-16 07:05 UTC by shiraosa

家具屋課題Homeのhtml初回提出になります。

やったこと
コードチェック
news,contact,recruitへのリンク

やってないこと
クラス名は随時追加もしくは削除する予定です。

2020-04-16 08:19 UTC, piasoratech requested changes
コメントしたので確認をお願いします

2020-04-16 08:19 UTC, piasoratech commented on html-kaguya/index.html
> +            <div class="h1-bg-color">
`h1`にクラスつけて色付けるじゃだめですかね？

2020-04-16 08:19 UTC, piasoratech commented on html-kaguya/index.html
> +                        <p><a href="news/news.html">アームストロングのテーブル入荷</a></p>
この画像はリンク貼らなくて大丈夫です

2020-04-16 08:29 UTC, shiraosa commented on html-kaguya/index.html
> +            <div class="h1-bg-color">
`h`タグがブロック要素であることが頭から抜け落ちてました！修正します！

2020-04-16 08:29 UTC, shiraosa commented on html-kaguya/index.html
> +                        <p><a href="news/news.html">アームストロングのテーブル入荷</a></p>
#に置き換えました

2020-04-16 08:31 UTC, shiraosa commented
不要な`div`の削除と一部のリンクを#に置き換えました。

2020-04-16 08:54 UTC, piasoratech commented on html-kaguya/index.html
> +                        <p><a href="news/news.html">アームストロングのテーブル入荷</a></p>
そもそもリンク扱いにしなくて良いので`a`タグを使わなくて良いです。

2020-04-16 08:56 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-04-16 08:56 UTC, piasoratech commented on html-kaguya/index.html
> +                    <div class="news-item-1">
class名のマジックナンバー(xxxx-1のようなもの)使用をやめましょう。

2020-04-16 08:56 UTC, piasoratech commented on html-kaguya/index.html
> +                        <p><a href="#">アームストロングのカウチ入荷</a></p>
返信でも書きましたが`a`タグ自体の使用が不要です。

2020-04-16 14:56 UTC, shiraosa commented
`a`タグの削除とクラス名の変更をしました。

2020-04-17 02:26 UTC, piasoratech approved these changes
良いかと！次に進みましょう！

2020-04-17 02:54 UTC, merged